### ISSUE TITLE
error in plugin

### ISSUE THREAD

**Issue by petemarkey** [jacopo-j/WebXDownloader#11]
record button does not show up.  see the following error.

Here is the link to the recorded webex:
https://athenahealth.webex.com/athenahealth/lsr.php?RCID=144b144b083fa5d84d7f3d709d6093f8

Windows 10 Pro/Chrome

![error](https://user-images.githubusercontent.com/66338013/130131159-9276a7de-7569-420c-80f0-c923b425f21a.JPG)

**Comment by jacopo-j** [comment]
Sorry, this extension does not support that kind of recordings (the kind that requires using the WebEx application or browser extension).

As always, PRs are welcome but I don't think this would be an easy one.
