### ISSUE TITLE
Extension is broken due to Webex player update

### ISSUE THREAD

**Issue by cad0p** [jacopo-j/WebXDownloader#13]

**Comment by cad0p** [comment]
url: https://politecnicomilano.webex.com/webappng/sites/politecnicomilano/recording/2876cded9f6e10398abf00505681040c/playback

**Comment by jacopo-j** [comment]
I will leave this issue open in case someone wants to submit a PR and fix it. Unfortunately I don't have time to fix it myself anytime soon.

**Comment by valerionew** [comment]
+1 for the issue, broken also for me, unfortunately i would not know where to start for the fix

**Comment by valerionew** [comment]
Hey guys! I asked for some help to @lorossi but we could not figure out how this works and how to debug it, so Lorenzo put together a small userscript that you load in tampermonkey and gets you 90% there 

Take it as a workaround until things aren't properly fixed here

https://gist.github.com/lorossi/94c08454c85cec8450f68b71dd6b1626

**Comment by lorossi** [comment]
I am working on a new extension. The first release works (not perfectly but it does the job).
https://github.com/lorossi/polimi-webex-downloader/

Feel free to give suggestions and code improvements as it's the first extension that I develop and I'm not completely sure I'm doing everything right!

**Comment by BorjaDG8** [comment]
Me gustaría dar las gracias a todas la personas que han hecho posible disponer de esta gran ayuda, en especial a @jacopo-j, @lorossi. Yo también tengo este error, el reproductor parece estar actualizada y ambas extensiones no me funcionan.

@lorossi he probado tu extensión y no me permite realizar la descarga. No me aparece el icono de descarga en el reproductor y en la ventana de la extensión no aparecen los vídeos. Si puedo ayudar en algo, estaré encantado!

Gracias chicos, para mi vuestro trabajo es fantástico!
![Captura](https://user-images.githubusercontent.com/98061825/150231318-d6bc9bde-8b23-4c01-92e1-d1a96c18027e.JPG)

**Comment by lorossi** [comment]
> Me gustaría dar las gracias a todas la personas que han hecho posible disponer de esta gran ayuda, en especial a @jacopo-j, @lorossi. Yo también tengo este error, el reproductor parece estar actualizada y ambas extensiones no me funcionan.
> 
> @lorossi he probado tu extensión y no me permite realizar la descarga. No me aparece el icono de descarga en el reproductor y en la ventana de la extensión no aparecen los vídeos. Si puedo ayudar en algo, estaré encantado!
> 
> Gracias chicos, para mi vuestro trabajo es fantástico! ![Captura](https://user-images.githubusercontent.com/98061825/150231318-d6bc9bde-8b23-4c01-92e1-d1a96c18027e.JPG)

Sadly I don't really speak spanish but as far as I can tell the download button is not appearing on that particular link right?
If so, open an issue on my repo ([here](https://github.com/lorossi/polimi-webex-downloader/issues)) and give me some more informations about it. Keep in mind that this only works on videos published by Politecnico di Milano.

**Comment by manolehaha** [comment]
> Hey guys! I asked for some help to @lorossi but we could not figure out how this works and how to debug it, so Lorenzo put together a small userscript that you load in tampermonkey and gets you 90% there
> 
> Take it as a workaround until things aren't properly fixed here
> 
> https://gist.github.com/lorossi/94c08454c85cec8450f68b71dd6b1626

how do we make it work? I have 0 knowledge lol and any help is appreciated. I tried @lorossi extension but still didn't work unfortunately. Thank you!

**Comment by jerrycool123** [comment]
For those who are desperate for downloading videos from Cisco Webex, a chrome extension called Video Downloader professional may be useful.

**Comment by Andrewsapo** [comment]
Io ancora non sono riuscito a risolvere. Ho installato anche il pacchetto di "Bebora" ma niente, il bottone di download non appare più.

**Comment by valerionew** [comment]
Io sto usando quella di @lorossi e funziona

**Comment by bebora** [comment]
> Io ancora non sono riuscito a risolvere. Ho installato anche il pacchetto di "Bebora" ma niente, il bottone di download non appare più.

Riesci a scrivermi il link della registrazione che non ti va? E magari anche che browser usi.

**Comment by Andrewsapo** [comment]
Ho fatto confusione, non ho installato il pacchetto di Bebora ma quello di lorossi "Webex-video-downloader v.0.20". Sto usando Chrome, però premetto che non ci inzuppo molto con queste cose quindi ci sta abbia semplicemente sbagliato qualche passaggio lol. Ho provato sia a lasciare sia Webxdownlaoder e Webex Video Downlaoder insieme che a rimuovere il primo e lasciare solo il secondo ma l'icona di download non mi appare più.

**Comment by bebora** [comment]
Sia il mio fix sia l'estensione suggerita da @valerionew aggiungono il tasto di download di fianco al titolo e non nel riquadro del player vero e proprio. Non ti appare proprio nulla?

**Comment by Andrewsapo** [comment]
> Sia il mio fix sia l'estensione suggerita da @valerionew aggiungono il tasto di download di fianco al titolo e non nel riquadro del player vero e proprio. Non ti appare proprio nulla?

No, nè nel player, nè nel filename. Però il tuo bebora onestamente non so come si installi, l'ho detto ne capisco proprio poco e niente di queste cose ahahah

**Comment by Andrewsapo** [comment]
> > Sia il mio fix sia l'estensione suggerita da @valerionew aggiungono il tasto di download di fianco al titolo e non nel riquadro del player vero e proprio. Non ti appare proprio nulla?
> 
> No, nè nel player, nè nel filename. Però il tuo bebora onestamente non so come si installi, l'ho detto ne capisco proprio poco e niente di queste cose ahahah

Edit: Sono riuscito a scaricare il tuo andando su Code-Download Zip in alto a destra. Però quando vado a su "Carica Estensione non Pacchettizzata" mi compare questo errore:
"File manifest mancante o illeggibile
Impossibile caricare il file manifest."

**Comment by bebora** [comment]
> > > Sia il mio fix sia l'estensione suggerita da @valerionew aggiungono il tasto di download di fianco al titolo e non nel riquadro del player vero e proprio. Non ti appare proprio nulla?
> > 
> > 
> > No, nè nel player, nè nel filename. Però il tuo bebora onestamente non so come si installi, l'ho detto ne capisco proprio poco e niente di queste cose ahahah
> 
> Edit: Sono riuscito a scaricare il tuo andando su Code-Download Zip in alto a destra. Però quando vado a su "Carica Estensione non Pacchettizzata" mi compare questo errore: "File manifest mancante o illeggibile Impossibile caricare il file manifest."

Prima devi estrarre lo zip in una cartella che vuoi. Poi quando ti fa scegliere da dove prendere l'estensione scegli la cartella che si chiama `src` all'interno dei file estratti dallo zip.

**Comment by Andrewsapo** [comment]
> > > > Sia il mio fix sia l'estensione suggerita da @valerionew aggiungono il tasto di download di fianco al titolo e non nel riquadro del player vero e proprio. Non ti appare proprio nulla?
> > > 
> > > 
> > > No, nè nel player, nè nel filename. Però il tuo bebora onestamente non so come si installi, l'ho detto ne capisco proprio poco e niente di queste cose ahahah
> > 
> > 
> > Edit: Sono riuscito a scaricare il tuo andando su Code-Download Zip in alto a destra. Però quando vado a su "Carica Estensione non Pacchettizzata" mi compare questo errore: "File manifest mancante o illeggibile Impossibile caricare il file manifest."
> 
> Prima devi estrarre lo zip in una cartella che vuoi. Poi quando ti fa scegliere da dove prendere l'estensione scegli la cartella che si chiama `src` all'interno dei file estratti dallo zip.

Dajeeeeeeeeeeeeeee ora funge, grazie mille!!!!!!!!!!

**Comment by jacopo-j** [comment]
The issue should now be fixed, thanks to @bebora and @sup3rgiu. Code on this repository should work again. Please give me some feedback (confirmation that everything works correctly), then I'll create a new release.

**Comment by bebora** [comment]
Tested and it works, LGTM.
