### ISSUE TITLE
its not working now...

### ISSUE THREAD

**Issue by nm4134** [jacopo-j/WebXDownloader#17]
hello,
I got this error, I wonder was if you may help on it.  Thanks.
he following exception was raised:

Cannot read properties of undefined (reading 'textContent')

**Comment by bebora** [comment]
Hi, the extension does not work for me as well, even though I get a different error message (`data.getElementsByTagName(...)[0] is undefined`). Are your videos publicly accessible? If so, would you mind posting here an example recording? Could you also write which browser you are using and the extension version you have currently installed?

**Comment by nm4134** [comment]
I have tried the latest Firefox and chrome on different PC and Mac but the result I got was the same.

Pass: vPEBD42K
https://chaochi.my.webex.com/chaochi.my/ldr.php?RCID=ccd7a7f86fc489bda2d290a7e9f59812

**Comment by bebora** [comment]
I made a PR that seems to be fixing the issue. You can wait for an official update from this repository or, if you are in a hurry, download it from [my fork](https://github.com/bebora/WebXDownloader/archive/refs/heads/new-player.zip).
