### ISSUE TITLE
Error occurred while processing the page

### ISSUE THREAD

**Issue by prakhar-ai** [jacopo-j/WebXDownloader#2]
I'm getting the error: "Some error occurred while processing the page. Maybe refresh and try again?" . Wasn't able to get it to work on both Chrome and Firefox

**Comment by jacopo-j** [comment]
Hello, please try to use extension debugging tools (https://extensionworkshop.com/documentation/develop/debugging/) and check the console for any error. I will need the output in order to check whats's wrong

**Comment by prakhar-ai** [comment]
I believe the problem lies when we get the meeting JSON data. Example: https://nirmauni.webex.com/webappng/api/v1/recordings/3d5e4e95246b475a80a7ce0b4da77625/stream?siteurl=nirmauni
This URL returns an error
I should also add that this meeting link is password protected.

Tried extension debugging
![error](https://user-images.githubusercontent.com/61567266/93904249-490ec000-fd17-11ea-852e-173bac54c8b7.png)

**Comment by jacopo-j** [comment]
Uhm, I'm pretty sure that error is not the cause. Does anything else appear while you reproduce the error? Make sure you make the console log persistent, otherwise it will reset every time the extension is reopened.

**Comment by prakhar-ai** [comment]
Understood the issue, in a password protected Webex Recording, you are supposed to pass the password as a header too.

Something like
headers = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "accesspwd": "RkQEgPG3",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
  }

**Comment by jacopo-j** [comment]
Ok, I will do some tests and try to add support to password-protected recording.

**Comment by jacopo-j** [comment]
@prakhar-ai turns out that those headers aren't needed. Only the header `appFrom: pb` is, for some reason. I think version 1.1.2 (coming up shortly) solves this issue.
