### ISSUE TITLE
From 01-05-2022 (recording audio)

### ISSUE THREAD

**Issue by Michele-Zhu** [jacopo-j/WebXDownloader#20]
For some reason WebXDownloader downloads has some audio problem, I mean on streaming it works fine but when downloaded some times videos has missing audio (no noise), just completely missing segments of audio of the recording at random.
Using: Google chrome, latest version of webxdownloader, vlc as media player

**Comment by bebora** [comment]
Hi, have you tried a different player? I have some reports that people are having problems with VLC, but other players seem to work.

**Comment by Michele-Zhu** [comment]
Yeah seems, an issue with VLC player, I'll close the issue thanks for the help dind't think about it since I dind't update it and was running just fine few weeks ago
