### ISSUE TITLE
there is an error, maybe the same of 2 weeks ago

### ISSUE THREAD

**Issue by Sam7269** [jacopo-j/WebXDownloader#4]
Can you check? this extension is saving lives ahah
keep up with the good work!

**Comment by jacopo-j** [comment]
Are you having problems with password protected recordings? If so, it's a known issue and I'm working on it.

**Comment by Sam7269** [comment]
Yes, but it seems that on Firefox it is working normally: i should try using it. I'll try also the debugging tool. 
Thanks anyway :D
