### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by lucaschalk** [jacopo-j/WebXDownloader#6]
I get this on Chrome:

Uncaught TypeError: Cannot read property '1' of null

Context
https://example-uni.webex.com/example-uni//ldr.php?RCID=abcdef12345

Stacktrace
content.js:3
"const SUBDOMAIN = MATCH[1];"

And no download function on chrome/firefox

**Comment by jacopo-j** [comment]
Hi, everything works fine for me on Firefox. Some thoughts:
- WebEx is having some troubles with recordings lately, at least according to PoliMi. Maybe try again in a different moment
- If the problem persists, it would be helpful to have the link to a recording to that I can verify what's happening
