### ISSUE TITLE
Can't Download password Protected meetings

### ISSUE THREAD

**Issue by KostaGorod** [jacopo-j/WebXDownloader#7]
I can provide the Link with the password if needed.
Received the known '"const SUBDOMAIN = MATCH[1];" error.

**Comment by jacopo-j** [comment]
Hi, this extension only works with recordings that use this kind of player interface:

<img width="1484" alt="Schermata 2021-05-23 alle 13 52 13" src="https://user-images.githubusercontent.com/9914547/119259337-1a125c00-bbce-11eb-812f-61681788402c.png">

Other, less common players such as this and those which play in full screen are currently not supported:

<img width="1428" alt="Schermata 2021-05-23 alle 13 56 30" src="https://user-images.githubusercontent.com/9914547/119259484-d835e580-bbce-11eb-9f79-ea5b68e14b10.png">

**Comment by KostaGorod** [comment]
It is using the supported player interface
On 5/23/2021 2:58:13 PM, Jacopo Jannone ***@***.***> wrote:
Hi, this extension only works with recordings that use this kind of player interface:
[Schermata 2021-05-23 alle 13 52 13] [https://user-images.githubusercontent.com/9914547/119259337-1a125c00-bbce-11eb-812f-61681788402c.png]
Other, less common players such as this and those which play in full screen are currently not supported:
[Schermata 2021-05-23 alle 13 56 30] [https://user-images.githubusercontent.com/9914547/119259484-d835e580-bbce-11eb-9f79-ea5b68e14b10.png]

**Comment by jacopo-j** [comment]
> It is using the supported player interface

Okay, then I will ask you to share the link and the password to the recording. You can send them to me privately if you prefer.

**Comment by jacopo-j** [comment]
Fixed in v. 1.2.1
