### ISSUE TITLE
Feature request: file name

### ISSUE THREAD

**Issue by valerionew** [jacopo-j/WebXDownloader#8]
Hey! I've been using your plugin for a while and i love it!  

Since often i'm dowloading many lessons at a time, i was wondering how difficult it would be to change the filename to the video title on webex instead of "merge_[...].mp4".

Thanks for your work!

**Comment by jacopo-j** [comment]
Hi, since the video file comes directly from Cisco's servers, I don't think there is an easy way to change the file name.

A possibility would be to download the whole video in the browser's local storage in the background and then initiate the browser download in order to save the file on disk (basically what MEGA does), but I'm not sure it's worth it.

I'll leave this issue open in case anyone has suggestions or wants to submit a PR.

**Comment by valerionew** [comment]
I'm not sure where is in the code that you are starting the download. If you have time, can you explain it? 
https://github.com/jacopo-j/WebXDownloader/blob/1e700e9f5a2cbd0f756ded4948d2c7dbcfd14c87/src/content.js#L37-L56
Is it here?

I'm trying my best to understand the plugin to see if i can suggest anything

**Comment by jacopo-j** [comment]
It's just a simple redirect: https://github.com/jacopo-j/WebXDownloader/blob/1e700e9f5a2cbd0f756ded4948d2c7dbcfd14c87/src/content.js#L53

**Comment by valerionew** [comment]
I think @lorossi was suggesting to put an `<a href="" download='FileName'>` and faking clicking on it with javascript, but i'll let him explain better

**Comment by jacopo-j** [comment]
Unfortunately that wouldn't work:

> * If the `Content-Disposition` header has different information from the `download` attribute, resulting behavior may differ:
>     * If the header specifies a `filename`, it takes priority over a filename specified in the `download` attribute.

[Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

Cisco's servers specify a `filename` header, so it takes priority.

**Comment by MillenniumEarl** [comment]
Hi @jacopo-j!

First of all, thanks for developing this extension, I am also using it to clog my computer with video lessons 😄

That said, I was able to solve the file naming problem, now the video is automatically downloaded with the name of the recording.

https://github.com/jacopo-j/WebXDownloader/blob/1e700e9f5a2cbd0f756ded4948d2c7dbcfd14c87/src/content.js#L36-L38
Here `data` contains the `recordName` property (which you had already used in `popup.js`).

Using the `chrome.downloads.download()` method in the background worker I was able to download the file with the desired name (I had to add the download permission in the manifest).

I have opened a pull request #9

**Comment by jacopo-j** [comment]
Excellent job! However, opening the popup now results in an error: `messages.map is not a function` (I haven't investigated further, maybe you know the reason).

Also, I would suggest the exception shown within the popup to be surrounded by `<pre>` or `<code>` tags and preceded by a message like "The following exception was raised:"

**Comment by MillenniumEarl** [comment]
Oh yes, my bad, I'm too used to typescript and haven't checked types 😅 

Just out of curiosity, how do you test the extension? Because I tried with a couple of video lessons but every time I have to log in and it becomes quite annoying to debug.

**Comment by jacopo-j** [comment]
No special way unfortunately, *it is* pretty annoying to debug

**Comment by MillenniumEarl** [comment]
@jacopo-j 
Ok, all fixed.

Looking for a while I found the method described [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension) in the chapter **Trying it out**, it is not really a debug but it allows you to fix the bulk of the problems

**Comment by jacopo-j** [comment]
Alright, I'll merge the PR and close this. Tomorrow I'll make a new release
